apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/helm-install@v1
        name: Helm dep
        kind: deploy
        with:
          release-name: release-mlcb
          chart-location: bitnami/mysql
