apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy-to-gke
on:
  push:
    branches:
      - "**"
jobs:
  gcloud:
    env:
      deploy: "true"
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Create credential file from secret
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy == 'true'}}
        name: Google Cloud authentication and HELM creation, install and port fwd
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm create what-the-helm
          helm install what-the-helm what-the-helm/
          sleep 30
          kubectl expose deployment what-the-helm222 --type LoadBalancer --port 80 --target-port 8080
                    
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy != 'true'}}
        name: Google Cloud authentication and HELM uninstall
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm uninstall what-the-helm
          